# Generated by Django 4.2.16 on 2026-03-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('RETURN_PENDING', 'Return Pending'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
