# Generated by Django 4.2.16 on 2026-03-17 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowing', '0002_alter_borrowrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitItemReturnApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('borrow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_item_approvals', to='borrowing.borrowrequest')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_return_approvals_confirmed', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_return_approvals', to='equipment.equipment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_return_approvals_to_confirm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('borrow_request', 'equipment')},
            },
        ),
    ]
