# Generated by Django 4.2.16 on 2026-03-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='return_condition',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='return_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('RETURN_PENDING', 'Return Pending'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
