# Generated by Django 4.2.29 on 2026-03-17 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('EQUIPMENT_CREATED', 'Equipment Created'), ('EQUIPMENT_UPDATED', 'Equipment Updated'), ('EQUIPMENT_DELETED', 'Equipment Deleted'), ('BORROW_REQUESTED', 'Borrow Requested'), ('BORROW_APPROVED', 'Borrow Approved'), ('BORROW_REJECTED', 'Borrow Rejected'), ('BORROW_RETURNED', 'Borrow Returned'), ('BORROW_OVERDUE', 'Borrow Overdue'), ('RESERVATION_CREATED', 'Reservation Created'), ('RESERVATION_CANCELLED', 'Reservation Cancelled'), ('CONSUMABLE_USED', 'Consumable Used'), ('CONSUMABLE_RESTOCKED', 'Consumable Restocked'), ('INCIDENT_REPORTED', 'Incident Reported'), ('INCIDENT_RESOLVED', 'Incident Resolved'), ('MAINTENANCE_SCHEDULED', 'Maintenance Scheduled'), ('MAINTENANCE_COMPLETED', 'Maintenance Completed'), ('USER_REGISTERED', 'User Registered'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('KIT_CREATED', 'Kit Created'), ('KIT_UPDATED', 'Kit Updated'), ('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('content_type_label', models.CharField(blank=True, max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
