# Generated by Django 4.2.16 on 2026-03-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Make this kit visible and borrowable by all members.'),
        ),
    ]
